name: Cron Job
'on':
  schedule:
    - cron: '*'
  workflow_dispatch: null
jobs:
  jest-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jest-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
