name: Jest-tests-run

on:
  workflow_dispatch:

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #Setup Node.js
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'

      #Install libraries
      - name: Install dependencies
        run: npm install 

      #Run tests
      - name: Run tests
        run: npm run test